package Generators;

public class Data {
    static String[] surnames = {
            "Florkowski",
            "Kuźnicki",
            "Łaba",
            "Kachel",
            "Drozdowski",
            "Mielczarek",
            "Ptasznik",
            "Chrostowski",
            "Długokęcki",
            "Patyk",
            "Jakóbczak",
            "Zając",
            "Wroński",
            "Rutkowski",
            "Kalbarczyk",
            "Polański",
            "Barszcz",
            "Warzecha",
            "Danielewicz",
            "Sobótka",
            "Adamowski",
            "Uznański",
            "Mroczek",
            "Łagoda",
            "Gulczyński",
            "Konarski",
            "Kieliszek",
            "Woronowicz",
            "Kasiński",
            "Sala",
            "Chrostek",
            "Orzechowski",
            "Tyc",
            "Matejko",
            "Kuźniewski",
            "Dobrzycki",
            "Martyniak",
            "Kołacz",
            "Rychter",
            "Gondek",
            "Kępa",
            "Nawrocki",
            "Kołodziej",
            "Rejman",
            "Gębka",
            "Ignasiak",
            "Spychalski",
            "Żydek",
            "Stachyra",
            "Krasiński",
            "Kudła",
            "Korzeniewski",
            "Jelonek",
            "Grocholski",
            "Oleszko",
            "Pastuszka",
            "Pakulski",
            "Rdzanek",
            "Staszczyk",
            "Garczyński",
            "Ptasiński",
            "Popowicz",
            "Duchnowski",
            "Śmigiel",
            "Brandys",
            "Palacz",
            "Rudnik",
            "Nogalski",
            "Korzec",
            "Kotowicz",
            "Kokot",
            "Tomas",
            "Terlecki",
            "Hadryś",
            "Wróbel",
            "Kondratowicz",
            "Rybakowski",
            "Pieczonka",
            "Kobiałka",
            "Manowski",
            "Stróżyński",
            "Grzesik",
            "Błaszkowski",
            "Lasota",
            "Szych",
            "Górzyński",
            "Springer",
            "Kęsik",
            "Kapela",
            "Mencel",
            "Gabriel",
            "Ambroziak",
            "Napiórkowski",
            "Machnio",
            "Szymala",
            "Majcher",
            "Hyla",
            "Ługowski",
            "Niedziółka",
            "Miś"
    };

    static String[] firstNames = {
            "Adam ",
            "Adrian ",
            "Adolf ",
            "Albert ",
            "Albin ",
            "Aleksander ",
            "Aleksy ",
            "Alfons ",
            "Alfred ",
            "Alojzy ",
            "Ambroży ",
            "Anatol ",
            "Andrzej ",
            "Antoni ",
            "Anzelm ",
            "Apolinary ",
            "Aureliusz ",
            "Arkadiusz ",
            "Artur ",
            "Augustyn ",
            "Bartosz ",
            "Bogdan ",
            "Bogusław ",
            "Bolesław ",
            "Cezary ",
            "Cyprian ",
            "Czesław ",
            "Damian ",
            "Daniel ",
            "Dariusz ",
            "Dawid ",
            "Dionizy ",
            "Dominik ",
            "Edward ",
            "Emil ",
            "Ernest ",
            "Eryk ",
            "Feliks ",
            "Filip ",
            "Fryderyk ",
            "Grzegorz ",
            "Gwidon ",
            "Henryk ",
            "Herbert ",
            "Ireneusz ",
            "Jacek ",
            "Jakub ",
            "Jan ",
            "Jarek ",
            "Jerzy ",
            "Juliusz ",
            "Kajetan ",
            "Kamil ",
            "Kacper ",
            "Karol ",
            "Kazimierz ",
            "Konrad ",
            "Krystian ",
            "Krzysztof ",
            "Lech ",
            "Leopold ",
            "Leszek ",
            "Lucjan ",
            "Łukasz ",
            "Maciej ",
            "Maksymilian ",
            "Marcin ",
            "Marek ",
            "Mariusz ",
            "Mateusz ",
            "Michał ",
            "Mikołaj ",
            "Mirosław ",
            "Norbert ",
            "Olgierd ",
            "Oskar ",
            "Paweł ",
            "Patryk ",
            "Piotr ",
            "Przemysław ",
            "Radosław ",
            "Rafał ",
            "Remigiusz ",
            "Robert ",
            "Roman ",
            "Sebastian ",
            "Sławomir ",
            "Stanisław ",
            "Stefan ",
            "Sylwek ",
            "Szymon ",
            "Tadeusz ",
            "Tomasz ",
            "Wacław ",
            "Waldemar ",
            "Wawrzyniec ",
            "Wiktor ",
            "Wincenty ",
            "Wit ",
            "Witold "
        };

    static String[] departmentNames = {
            "IT department",
            "Promotion department",
            "Finance department",
            "Cleaning department",
            "Electrical equipment department"
    };
    
    static String[] subjectNames = {
            "Ancient Greek",
            "Animal husbandry",
            "Art",
            "Biology",
            "Chemistry",
            "Commerce",
            "Computer studies.",
            "Design technology",
            "Drama",
            "Ethic(s)",
            "Food technology",
            "Geography",
            "Health and hygiene",
            "Latin",
            "Literature",
            "Music",
            "Physics",
            "Religion",
            "Woodwork",
            "Sociology",
            "Psychology",
    };
}
